// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CaptureSnapshot(arg1:string,arg2:boolean,arg3:string):Promise<model.VersionMeta>;

export function CompareVersions(arg1:string,arg2:string,arg3:string):Promise<model.DiffResult>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteSnapshot(arg1:string,arg2:string):Promise<void>;

export function ExportSQLFile(arg1:string,arg2:string):Promise<string>;

export function GetConnections():Promise<Array<model.ConnectionConfig>>;

export function ListSnapshots(arg1:string):Promise<Array<model.VersionMeta>>;

export function SaveConnection(arg1:model.ConnectionConfig):Promise<void>;

export function TestConnection(arg1:model.ConnectionConfig):Promise<model.ConnectionTestResult>;
