// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['CaptureSnapshot'](arg1, arg2, arg3);
}

export function CompareVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareVersions'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteSnapshot(arg1, arg2) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1, arg2);
}

export function ExportSQLFile(arg1, arg2) {
  return window['go']['main']['App']['ExportSQLFile'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function ListSnapshots(arg1) {
  return window['go']['main']['App']['ListSnapshots'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
